// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7ulbLrAFldMflaFbpFEH7Upipcd4c6Q',
    appId: '1:1007448672439:web:0ef1f63e0fb9bbcf95e532',
    messagingSenderId: '1007448672439',
    projectId: 'flutterfire-ui-codelab-93bd8',
    authDomain: 'flutterfire-ui-codelab-93bd8.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-93bd8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8bETjyRFnUBEuQ-TxrXhT8vh9uLNW56s',
    appId: '1:1007448672439:android:5d2dfe6d2d3b3da295e532',
    messagingSenderId: '1007448672439',
    projectId: 'flutterfire-ui-codelab-93bd8',
    storageBucket: 'flutterfire-ui-codelab-93bd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMkMPYWveFS2plrEBuaGjA5ysobPHVI0Q',
    appId: '1:1007448672439:ios:cdbd6d0359bbee3895e532',
    messagingSenderId: '1007448672439',
    projectId: 'flutterfire-ui-codelab-93bd8',
    storageBucket: 'flutterfire-ui-codelab-93bd8.appspot.com',
    androidClientId:
        '1007448672439-5hkuteua0b7qntqn1o75lo1ccijnduqj.apps.googleusercontent.com',
    iosClientId:
        '1007448672439-asod917u1jg5nslkhno61694dabthtd1.apps.googleusercontent.com',
    iosBundleId: 'com.example.myartist',
  );

  static void signIn() {
    FirebaseAuth.instance.signInWithEmailAndPassword(
        email: "firebase.ff@gmail.com", password: "f1reb@s3");
  }
}
